# This workflow will build and unit test the project, and is triggered by
# pushes and pull requests.

name: Build & Test

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]
  workflow_dispatch:
    # Allow workflow to be triggered manually.

jobs:
  build:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    name: Build & Test (Java ${{matrix.java-version}})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: ['8', '11']

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Java ${{matrix.java-version}}
      uses: actions/setup-java@v3 
      with:
        java-version: ${{matrix.java-version}}
        distribution: 'adopt'
        cache: 'maven'

    - name: Build & Unit Test w/Maven
      # temporarily skip tests to speed up builds while working on ghactions
      run: mvn -B clean package -DskipTests
