# This workflow is responsible for:
# - publishing artifacts to Maven Central
# - building and publishing javadocs to the git repository.
# It is triggered when a new release is created.

name: Publish Release
on:
  release:
    types: [created]
  workflow_dispatch:
    # Allow this workflow to be triggered manually

jobs:
  publish:
    name: Publish Release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Java 
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'adopt'
        cache: 'maven'
        # Configure ~/.m2/settings.xml
        server-id: ossrh
        server-username: MAVEN_USERNAME
        server-password: MAVEN_PASSWORD
        # import GPG key into build agent's local keystore
        gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
        gpg-passphrase: ${{ secrets.GPG_PASSPHRASE }}

    - name: Set artifact version
      run: |
        mvn versions:set -DnewVersion=${GITHUB_REF_NAME} -DgenerateBackupPoms=false
        echo "Set artifact version to: ${GITHUB_REF_NAME}"

    - name: Publish javadocs to Github Pages
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        GH_REPO_SLUG: ${{ github.repository }}
        GH_TAG: ${{ github.ref_name}}
      run: |
        mvn clean javadoc:javadoc
        build/publishJavadoc-gha.sh

    - name: Publish artifacts to Maven Central
      env:
        MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
        MAVEN_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
        GPG_KEYNAME: ${{ secrets.GPG_KEYNAME }}
        GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
      run: |
        echo "Publishing to maven central using username: ${MAVEN_USERNAME}"
        # build only the "verify" goal for now until we're brave enough to try to deploy to MC :)
        mvn -B verify
