# This workflow runs semantic-release to potentially create a new tagged release
# for the project, depending on the commit messages since the last release.
# It is triggered by a successful completion of the 'Build & Test' workflow on the main branch.
# If semantic-release determines that a new release is needed and pushes a new tag to the
# repo, the next workflow will be triggered to publish the tagged release on Maven Central.

name: Create Release

on:
  workflow_run:
    workflows: ['Build & Test']
    branches: ['main']
    types:
      - completed
  workflow_dispatch:
    # Allow this workflow to be triggered manually

jobs:
  semrel:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    name: Create Release
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3


    - name: Setup node.js
      uses: actions/setup-node@v3
      with:
        node-version: 14

    - name: Set up python
      uses: actions/setup-python@v4
      with:
        python-version: 3.8

    - name: Install semantic-release 
      run: |
        npm install -g semantic-release
        npm install -g @semantic-release/changelog
        npm install -g @semantic-release/exec
        npm install -g @semantic-release/git
        npm install -g @semantic-release/github
        npm install -g @semantic-release/commit-analyzer
        pip install --user bump2version

    - name: Create & Tag Release
      if: ${{ github.event.workflow_run.conclusion == 'success' }}
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: npx semantic-release
